title: Srishti Chandana
theme: minima
markdown: kramdown
collections:
  projects:
    output: true
    permalink: /projects/:name/

header_pages:
  - index.md
  - projects/index.md
  - writing/index.md
  - about.md
  - contact.md
